version: '3.4'
services:
  thehive:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env.txt
    restart: "no"
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
